apiVersion: v1
kind: Endpoints
metadata:
  namespace: kubemark
  name: kube-apiserver
  labels:
    k8s-app: kube-apiserver
subsets:
  - addresses:
      - ip: {{.KubemarkMasterClusterIp}}
    ports:
      - name: https
        port: 443
