apiVersion: v1
kind: Service
metadata:
  namespace: kubemark
  name: kube-apiserver
  labels:
    k8s-app: kube-apiserver
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: https
      port: 443
