apiVersion: v1
kind: Pod
metadata:
  name: pod-churn-{{.Index}}
  labels:
    group: {{.Group}}  
spec:
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: direct-scheduler-throughput-pod-pvc-{{.Index}}
  containers:
  - image: registry.k8s.io/pause:3.9
    name: pause
    volumeMounts:
        - name: storage
          mountPath: /home/node
          subPath: home
