{
 "title": "API Server Metrics",
 "tags": [
  "kubernetes",
  "scalability",
  "perf-analysis"
 ],
 "time": { "from": "2026-07-03T00:00:00Z", "to": "2026-07-22T23:59:59Z" },
 "templating": {
  "list": [
   { "name": "run", "label": "Scale Run", "query": "label_values(run)" },
   {
    "name": "resource",
    "label": "Resource",
    "query": "label_values(apiserver_request_total, resource)"
   },
   {
    "name": "verb",
    "label": "Verb",
    "query": "label_values(apiserver_request_total, verb)"
   },
   {
    "name": "step",
    "label": "Step",
    "query": "label_values(apiserver_log_traces_duration_seconds_bucket{run=~\"^$run$\"}, step)"
   }
  ]
 },
 "panels": [
  { "title": "SLO Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "P99 Get Latency | Resource Scope",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 1, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_sli_duration_seconds_bucket{verb=\"GET\", scope=\"resource\", resource=~\"$resource\", run=~\"^$run\"}[1m])) by (le, resource))",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "P99 List Latency | Namespace Scope",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 1, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_sli_duration_seconds_bucket{verb=\"LIST\", scope=\"namespace\", resource=~\"$resource\", run=~\"^$run\"}[1m])) by (le, resource))",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "P99 List Latency | Cluster Scope",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 9, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_sli_duration_seconds_bucket{verb=\"LIST\", scope=\"cluster\", resource=~\"$resource\", run=~\"^$run\"}[1m])) by (le, resource))",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "P99 Write Latency",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 9, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_sli_duration_seconds_bucket{verb=~\"POST|PUT|PATCH|DELETE|APPLY\", resource=~\"$resource\", run=~\"^$run\"}[1m])) by (le, resource, verb))",
     "legendFormat": "{{resource}} - {{verb}}"
    }
   ]
  },
  {
   "title": "Additional API & Cluster Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "Request Volume by Verb",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 18, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{resource=~\"$resource\",verb=~\"$verb\", run=~\"^$run\"}[1m])) by (verb)",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "Request Volume by Resource",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 18, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{resource=~\"$resource\",verb=~\"$verb\", run=~\"^$run\"}[1m])) by (resource)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "HTTP Errors",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 26, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{code!~\"2..|3..\",resource=~\"$resource\",verb=~\"$verb\", run=~\"^$run\"}[1m])) by (code, resource, verb)",
     "legendFormat": "HTTP {{code}} - {{resource}} ({{verb}})"
    }
   ]
  },
  {
   "title": "Watch Terminations",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 26, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_terminated_watchers_total{resource=~\"$resource\", run=~\"^$run\"}[1m])) by (resource)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "watchCache Lock Wait Time",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 34, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_watch_cache_read_wait_seconds_bucket{resource=~\"$resource\", run=~\"^$run\"}[1m])) by (le, resource))",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "APF Queue Length",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 34, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (priority_level) (apiserver_flowcontrol_current_inqueue_requests{run=~\"^$run\"})",
     "legendFormat": "{{priority_level}}"
    }
   ]
  },
  { "title": "API Server Log Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Slow Trace Duration (99th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_log_traces_duration_seconds_bucket{resource=~\"$resource\", step=~\"$step\", run=~\"^$run$\"}[1m])) by (le, name, step, resource))",
     "legendFormat": "{{name}} - {{step}} - {{resource}}"
    }
   ]
  },
  {
   "title": "Slow Trace Occurrence Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_log_traces_duration_seconds_count{resource=~\"$resource\", step=~\"$step\", run=~\"^$run$\"}[1m])) by (name, step, resource)",
     "legendFormat": "{{name}} - {{step}} - {{resource}}"
    }
   ]
  }
 ]
}