{
 "title": "Write Throughput",
 "tags": [
  "perflens",
  "kubernetes",
  "scale",
  "write-throughput",
  "watch"
 ],
 "time": { "from": "2026-08-05T19:20:55.755Z", "to": "2026-08-05T19:28:50.514Z" },
 "templating": {
  "list": [
   { "name": "run", "label": "Scale Run", "query": "label_values(run)" },
   {
    "name": "resource",
    "label": "Resource",
    "query": "label_values(apiserver_request_total{run=~\"^$run$\"}, resource)"
   }
  ]
 },
 "panels": [
  {
   "title": "Incomming requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (resource,  subresource, verb, scope) (rate(apiserver_request_duration_seconds_count{resource=~\"$resource\",verb=\"PATCH\", subresource=\"\", run=~\"^$run\"}[1m]))",
     "legendFormat": "{{resource}} {{verb}}"
    },
    {
     "expr": "sum by (resource,  subresource, verb, scope) (rate(apiserver_request_duration_seconds_count{resource=~\"$resource\",verb=\"PATCH\", subresource!=\"\", run=~\"^$run\"}[1m]))",
     "legendFormat": "{{resource}}/{{subresource}} {{verb}}"
    }
   ]
  },
  {
   "title": "Opened watches",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (resource)(apiserver_longrunning_requests{verb=\"WATCH\", resource=~\"$resource\", run=~\"^$run\"})",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "API server watch cache delay",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "((scalar(max(etcd_debugging_mvcc_current_revision{run=~\"^$run\"})) - max by (resource) (apiserver_watch_cache_resource_version{resource=~\"$resource\", run=~\"^$run\"})) / scalar(max(deriv(etcd_debugging_mvcc_current_revision{run=~\"^$run\"}[15s])) > 0))",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (resource, verb, code) (rate(apiserver_request_total{resource=~\"$resource\", verb=\"PATCH\", code!~\"2..\", run=~\"^$run\"}[1m]))\n/ ignoring(code) group_left\nsum by (resource, verb) (rate(apiserver_request_total{resource=~\"$resource\", verb=\"PATCH\", run=~\"^$run\"}[1m]))",
     "legendFormat": "{{resource}} {{verb}} {{code}} "
    },
    {
     "expr": "sum by (resource, verb, subresource, code) (rate(apiserver_request_total{resource=~\"$resource\", verb=\"PATCH\", code!~\"2..\", run=~\"^$run\"}[1m]))\n/ ignoring(code) group_left\nsum by (resource, verb, subresource) (rate(apiserver_request_total{resource=~\"$resource\", verb=\"PATCH\", run=~\"^$run\"}[1m]))",
     "legendFormat": "{{resource}}/{{subresource}} {{verb}} {{code}}"
    }
   ]
  },
  {
   "title": "Watch data rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (resource) (rate(apiserver_watch_events_sizes_sum{resource=~\"$resource\", run=~\"^$run\"}[1m]))",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Informer delay",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "((scalar(max(etcd_debugging_mvcc_current_revision{run=~\"^$run\"})) - max by (resource, name) (informer_store_resource_version{resource=~\"$resource\", run=~\"^$run\"})) / scalar(max(deriv(etcd_debugging_mvcc_current_revision{run=~\"^$run\"}[30s])) > 0))",
     "legendFormat": "{{name}} {{resource}}"
    }
   ]
  },
  {
   "title": "APIServer Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{resource=~\"$resource\",verb=\"PATCH\",subresource=\"\", run=~\"^$run\"}[1m])) by (resource,  subresource, verb, scope, le))",
     "legendFormat": "{{resource}} {{verb}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{resource=~\"$resource\",verb=\"PATCH\",subresource!=\"\", run=~\"^$run\"}[1m])) by (resource,  subresource, verb, scope, le))",
     "legendFormat": "{{resource}}/{{subresource}} {{verb}}"
    }
   ]
  },
  {
   "title": "Watch event dispatched",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(apiserver_watch_cache_events_dispatched_total{resource=~\"$resource\", run=~\"^$run\"}[1m])",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max by (pod) (rate(container_cpu_usage_seconds_total{exported_namespace=\"kube-system\",container!=\"\", run=~\"^$run\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Etcd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Etcd client latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (resource, operation, le) (rate(etcd_request_duration_seconds_bucket{resource=~\"$resource\", run=~\"^$run\"}[1m])))",
     "legendFormat": "p99 {{resource}} {{operation}}"
    }
   ]
  },
  {
   "title": "Resource Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max by (resource) (apiserver_resource_size_estimate_bytes{resource=~\"$resource\", run=~\"^$run\"})",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Etcd size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "etcd_mvcc_db_total_size_in_bytes{run=~\"^$run\"}",
     "legendFormat": "total"
    },
    {
     "expr": "etcd_mvcc_db_total_size_in_use_in_bytes{run=~\"^$run\"}",
     "legendFormat": "usage"
    },
    {
     "expr": "etcd_server_quota_backend_bytes{run=~\"^$run\"}",
     "legendFormat": "quota"
    }
   ]
  },
  {
   "title": "Etcd server latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (type,le) (rate(etcd_server_request_duration_seconds_bucket{run=~\"^$run\"}[1m])))",
     "legendFormat": "p99 {{type}}"
    }
   ]
  },
  {
   "title": "Resource Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max by (resource) (apiserver_resource_size_estimate_bytes{resource=~\"$resource\", run=~\"^$run\"})",
     "legendFormat": "{{resource}}"
    }
   ]
  }
 ]
}