apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Name}}
{{if not (eq (Mod .Index 20) 0 19) }} # .Index % 20 in {0,19} - only 10% deployments will have non-immutable ConfigMap.
immutable: true
{{end}}
# Every pod that needs its own configmap entry should be unconditionally
# added below. That allows us to avoid complicating it with ifs.
data:
  # all-queries is used by DNS tests. Since dnsperfgo counts NXDOMAINs as errors, this config contains only valid names.
  all-queries: |
      kubernetes.default
      google.com
      8.8.8.8
      metrics-server.kube-system
      metadata.google.internal
