{{$SetServiceProxyLabel := DefaultParam .SetServiceProxyLabel false}}

apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
  labels:
    service.kubernetes.io/service-proxy-name: foo
    app: dns-perf-client
spec:
  selector:
    svc: {{.Name}}
    app: dns-perf-client
  ports:
  - port: 80
    targetPort: 80
