apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: preload
  namespace: preload
spec:
  selector:
    matchLabels:
      name: preload
  template:
    metadata:
      labels:
        name: preload
    spec:
      initContainers:
      {{range $idx, $image := .Images}}
      - name: preload-{{$idx}}
        image: docker
        command: ["sh", "-c", "docker pull {{$image}} 2>&1 | tee /var/log/cl2-image-preload-{{$idx}}.log"]
        volumeMounts:
        - name: docker
          mountPath: /var/run
        - name: logs-volume
          mountPath: /var/log
      {{end}}
      volumes:
      - name: docker
        hostPath:
          path: /var/run
      - name: logs-volume
        hostPath:
          path: /var/log
      containers:
      - name: pause
        image: gcr.io/google_containers/pause

