run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - gofmt
#    - gosimple
#    - govet
#    - ineffassign
#    - staticcheck
#    - structcheck
    - typecheck
#    - unused
#    - varcheck
#    - golint
#    - deadcode
#    - errcheck