run:
  timeout: 10m

linters-settings:
  golint:
    min-confidence: 0
  misspell:
    locale: US
  govet:
    check-shadowing: false
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    # TODO(kushthedude) remove the disabled checks
    disable:
      - composites
      - copylocks

linters:
  disable-all: true
  enable:
    - gofmt
    - revive
    - govet
    - errcheck
    - deadcode
    # TODO(kushthedude) fix after vendor is migrated to go modules
    # - misspell

service:
  golangci-lint-version: 1.23.x # use the fixed version to not introduce new linters unexpectedly
  prepare:
    - echo "here I can run custom commands, but no preparation needed for this repo"
