version: "2"

run:
  timeout: 10m

linters:
  default: none
  enable:
    # TODO(wojtek-t): Reenable after fixing existing issues.
    # - revive
    - govet
    # TODO(wojtek-t): Reenable after fixing existing issues.
    # - errcheck
    - unused
    - misspell
  settings:
    errcheck:
      # Workaround for https://github.com/golangci/golangci-lint/issues/4733
      ignore: ""
    golint:
      min-confidence: 0
    misspell:
      locale: US
    govet:
      check-shadowing: false
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf

formatters:
  enable:
    - gofmt

service:
  golangci-lint-version: 1.51.x # use the fixed version to not introduce new linters unexpectedly
  prepare:
    - echo "here I can run custom commands, but no preparation needed for this repo"
