apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-resource-state-metrics
  namespace: custom-resource-state-metrics-perf-test
  labels:
    app.kubernetes.io/name: custom-resource-state-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: custom-resource-state-metrics
  template:
    metadata:
      labels:
        app.kubernetes.io/name: custom-resource-state-metrics
    spec:
      serviceAccountName: custom-resource-state-metrics
      containers:
      - name: kube-state-metrics
        image: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.8.0
        args:
        - --custom-resource-state-only
        - --custom-resource-state-config=/etc/config/config.yaml
        - --port=8080
        - --telemetry-port=8081
        ports:
        - name: http-metrics
          containerPort: 8080
        - name: telemetry
          containerPort: 8081
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: custom-resource-state-metrics-config