{{$replicas := DefaultParam .Replicas 1}}
{{$version := DefaultParam .Version "3.7.2-0"}}
{{$imageRegistry := DefaultParam .EtcdImageRegistry "registry.k8s.io/etcd"}}
{{$quotaBackendBytes := DefaultParam .QuotaBackendBytes "34359738368"}}
{{$storageSize := DefaultParam .StorageSize ""}}
{{$storageClass := DefaultParam .StorageClass ""}}

apiVersion: operator.etcd.io/v1alpha1
kind: EtcdCluster
metadata:
  name: {{.Name}}
spec:
  size: {{$replicas}}
  version: "{{$version}}"
  imageRegistry: "{{$imageRegistry}}"
  etcdOptions:
  - "--quota-backend-bytes={{AddInt $quotaBackendBytes 0}}"
  - "--metrics=extensive"
{{if $storageSize}}
  storageSpec:
    volumeSizeRequest: "{{$storageSize}}"
{{if $storageClass}}
    storageClassName: "{{$storageClass}}"
{{end}}
{{end}}
