{{$replicas := DefaultParam .Replicas 3}}
{{$version := DefaultParam .Version "3.5.15-0"}}
{{$imageRegistry := DefaultParam .EtcdImageRegistry "registry.k8s.io/etcd"}}

apiVersion: operator.etcd.io/v1alpha1
kind: EtcdCluster
metadata:
  name: {{.Name}}
spec:
  size: {{$replicas}}
  version: "{{$version}}"
  imageRegistry: "{{$imageRegistry}}"
