apiVersion: extensions.agents.x-k8s.io/v1alpha1
kind: SandboxTemplate
metadata:
  name: load-test-template
spec:
  podTemplate:
    metadata:
      labels:
        app: agent-sandbox-load-test
    spec:
      containers:
      - name: sandbox
        image: alpine
        command: ["/bin/sh", "-c", "echo 'Hello from the Agent Sandbox!'; sleep 28800"]
