apiVersion: extensions.agents.x-k8s.io/v1alpha1
kind: SandboxWarmPool
metadata:
  name: warmpool-{{.Index}}
spec:
  sandboxTemplateRef:
    name: template-{{.Index}}
  replicas: {{DefaultParam .CL2_WARMPOOL_SIZE 200}}
