apiVersion: v1
kind: Pod
metadata:
  name: {{.Name}}
  labels:
    group: sandbox
spec:
  containers:
  - name: sandbox
    image: registry.k8s.io/e2e-test-images/agnhost:2.40
    command: ['/bin/sh', '-c', 'until /agnhost connect gateway-svc-0.agentic-gateway-0.svc.cluster.local:80; do sleep 1; done; exec sleep 3600']
    readinessProbe:
      exec:
        command: ['/agnhost', 'connect', 'gateway-svc-0.agentic-gateway-0.svc.cluster.local:80']
      initialDelaySeconds: 1
      periodSeconds: 2
    resources:
      requests:
        cpu: "{{.CpuRequest}}"
        memory: "{{.MemoryRequest}}"
      limits:
        cpu: "{{.CpuLimit}}"
        memory: "{{.MemoryLimit}}"
