// Code generated by "stringer -type=status"; DO NOT EDIT.

package util

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Terminating-1]
	_ = x[RunningAndReady-2]
	_ = x[RunningButNotReady-3]
	_ = x[PendingScheduled-4]
	_ = x[PendingNotScheduled-5]
	_ = x[Inactive-6]
}

const _status_name = "UnknownTerminatingRunningAndReadyRunningButNotReadyPendingScheduledPendingNotScheduledInactive"

var _status_index = [...]uint8{0, 7, 18, 33, 51, 67, 86, 94}

func (i status) String() string {
	if i < 0 || i >= status(len(_status_index)-1) {
		return "status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _status_name[_status_index[i]:_status_index[i+1]]
}
