---
# Source: kwok/templates/role_binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kwok-controller
  labels:
    helm.sh/chart: kwok-0.2.0
    app.kubernetes.io/name: kwok
    app.kubernetes.io/instance: kwok-controller
    app.kubernetes.io/version: "v0.7.0"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kwok-controller
subjects:
- kind: ServiceAccount
  name: kwok-controller
  namespace: kwok-system
