---
# Source: kwok/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kwok-controller
  namespace: kwok-system
  labels:
    helm.sh/chart: kwok-0.2.0
    app.kubernetes.io/name: kwok
    app.kubernetes.io/instance: kwok-controller
    app.kubernetes.io/version: "v0.7.0"
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
  - name: http
    port: 10247
    protocol: TCP
    targetPort: 10247
  selector:
    app.kubernetes.io/name: kwok
    app.kubernetes.io/instance: kwok-controller
  type: ClusterIP
