apiVersion: v1
kind: Pod
metadata:
  generateName: eks-pod-identity-pod-churn-
  labels:
    group: {{.Group}}
spec:
  containers:
  - image: registry.k8s.io/pause:3.9
    name: pause
  initContainers:
  - name: app-init
    image: amazon/aws-cli:latest
    command: ["/bin/sh"]
    args: ["-c", "aws sts get-caller-identity"]
