{{$TURN_OFF_LOGGING_TO_FILE := DefaultParam .TURN_OFF_LOGGING_TO_FILE false}}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: probes
  name: ping-client
  labels:
    probe: ping-client
spec:
  selector:
    matchLabels:
      probe: ping-client
  replicas: {{.Replicas}}
  template:
    metadata:
      labels:
        probe: ping-client
    spec:
      containers:
        - name: ping-client
          image: gcr.io/k8s-testimages/probes:v0.0.4
          args:
            - --metric-bind-address=0.0.0.0:8080
            - --mode=ping-client
            - --ping-server-address=ping-server:8081
{{if $TURN_OFF_LOGGING_TO_FILE}}
            - --logtostderr=true
{{else}}
            - --logtostderr=false
            - --log_file=/var/log/cl2-ping-client.log
{{end}}
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8080
              name: metrics
{{if $TURN_OFF_LOGGING_TO_FILE}}
          volumeMounts:
            - name: logs-volume
              mountPath: /var/log
      volumes:
        - name: logs-volume
          hostPath:
            path: /var/log
{{end}}
