ClusterLoader:
  delete: true
  projects:
    - num: 1
      basename: clusterproject
      tuning: default
      RCs:
        - num: 5
          image: k8s.gcr.io/pause-amd64:3.0
          basename: pausepods
          label: purpose=test
    - num: 2
      basename: zip
      tuning: default
      RCs:
        - num: 5
          image: k8s.gcr.io/pause-amd64:3.0
          basename: pausepods
    - num: 2
      basename: zip
      tuning: default
      RCs:
        - num: 1
          image: k8s.gcr.io/pause-amd64:3.0
          basename: grumble
          label: app=grumble
  tuningsets:
    - name: default
      pods:
        stepping:
          stepsize: 10
          pause: 30s
        ratelimit:
          delay: 100ms
      project:
        ratelimit:
          delay: 10s
