# Default parameters that explores performance space given limited CPU.

# Number of seconds to run with a particular setting.
run_length_seconds: [600]
# cpu limit for coredns, null means unlimited.
coredns_cpu: [200, 250, 300, null]
# size of coredns cache. Note: 10000 is the maximum. 0 to disable caching.
coredns_cache: [0, 10000]
# Maximum QPS for dnsperf. dnsperf is self-pacing and will ramp request rate
# until requests are dropped. null means no limit.
max_qps: [null]
# File to take queries from. This is in dnsperf format.
query_file: ["all-queries.txt"]
