{{$EnablePVs := DefaultParam .ENABLE_PVS false}}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Name}}
  labels:
    group: statefulset
spec:
  selector:
    matchLabels:
      name: {{.Name}}
  serviceName: {{.Name}}
  replicas: {{RandIntRange .ReplicasMin .ReplicasMax}}
  template:
    metadata:
      labels:
        group: statefulset
        name: {{.Name}}
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: {{.Name}}
        image: k8s.gcr.io/pause:3.1
        ports:
          - containerPort: 80
            name: web
        {{if $EnablePVs}}
        volumeMounts:
          - name: pv
            mountPath: /var/pv
        {{end}}
        resources:
          requests:
            cpu: 10m
            memory: "10M"
  {{if $EnablePVs}}
  volumeClaimTemplates:
    - metadata:
        name: pv
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Mi
  {{end}}
