apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Name}}
  labels:
    group: test-job
    job-type: short-lived
spec:
  parallelism: {{.Replicas}}
  completions: {{.CompletionReplicas}}
  completionMode: {{.Mode}}
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        group: test-pod
        job-type: short-lived
    spec:
      restartPolicy: Never
      containers:
        - name: {{.Name}}
          image: registry.k8s.io/e2e-test-images/agnhost:2.56
          command:
          - sleep
          - {{.Sleep}}
          resources:
            claims:
            - name: gpu
      resourceClaims:
      - name: gpu
        resourceClaimTemplateName: single-gpu-0