apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Name}}
  labels:
    group: test-job
    job-type: short-lived
spec:
  parallelism: {{.Replicas}}
  completions: {{.CompletionReplicas}}
  completionMode: {{.Mode}}
  # In tests involving a large number of sequentially created, short-lived jobs, the spin-up time may be significant.
  # A TTL of 1 hour should be sufficient to retain the jobs long enough for measurement checks.
  ttlSecondsAfterFinished: 3600 # 1 hour
  template:
    metadata:
      labels:
        group: test-pod
        job-type: short-lived
    spec:
      restartPolicy: Never
      containers:
        - name: {{.Name}}
          image: gcr.io/k8s-staging-perf-tests/sleep:v0.0.3
          args:
            - {{.Sleep}}
          resources:
          {{ if .ExtendedResource }}
            limits:
              example.com/gpu: "1"
          {{ else }}
            claims:
            - name: gpu
      resourceClaims:
      - name: gpu
        resourceClaimTemplateName: single-gpu-0
         {{ end }}
