apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: {{.Name}}
spec:
  spec:
    devices:
      requests:
        - name: gpu
          exactly:
            deviceClassName: gpu.example.com