{{$CpuRequest := DefaultParam .CpuRequest "10m"}}
{{$MemoryRequest := DefaultParam .MemoryRequest "10M"}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}
  labels:
    group: load
spec:
  replicas: {{.InstanceCount}}
  selector:
    matchLabels:
      name: {{.Name}}
  template:
    metadata:
      labels:
        name: {{.Name}}
        svc: svc
    spec:
      containers:
      - image: alpine:3.7
        name: {{.Name}}
        command: ["/bin/sh"]
        args:
          - -c
          - "sleep 10h"
        env:
        - name: REVISION
          value: {{.Revision}}
        resources:
          requests:
            cpu: {{$CpuRequest}}
            memory: {{$MemoryRequest}}
        # Approx. 50% of all pods is unhealthy. Changes every 30s.
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "test 5 -lt $((RANDOM%10))"
          periodSeconds: 30
          failureThreshold: 1
          successThreshold: 1
      dnsPolicy: Default
      terminationGracePeriodSeconds: 1
      # Add not-ready/unreachable tolerations for 15 minutes so that node
      # failure doesn't trigger pod deletion.
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 900
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 900