{{$image := DefaultParam .CL2_BENCHMARK_IMAGE "gcr.io/k8s-staging-perf-tests/perf-tests-util/request-benchmark:v0.0.23"}}
{{$imagePullPolicy := DefaultParam .CL2_IMAGE_PULL_POLICY "IfNotPresent"}}
{{$endpoints := DefaultParam .Endpoints "http://etcd-cluster-0:2379"}}
{{$qps := DefaultParam .Qps 0}}
{{$concurrency := DefaultParam .Concurrency 50}}
{{$keyCount := DefaultParam .KeyCount 10000}}
{{$keyPrefix := DefaultParam .KeyPrefix "/registry/pods/default/pod-"}}
{{$payloadType := DefaultParam .PayloadType "pod"}}
{{$cpu := DefaultParam .cpu "1000m"}}
{{$memory := DefaultParam .memory "512Mi"}}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Name}}
  labels:
    group: benchmark-init
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        name: {{.Name}}
        group: benchmark-init
    spec:
      restartPolicy: OnFailure
      containers:
      - name: etcd-init
        image: {{$image}}
        imagePullPolicy: {{$imagePullPolicy}}
        args:
        - etcd-put
        - --endpoints={{$endpoints}}
        - --qps={{$qps}}
        - --concurrency={{$concurrency}}
        - --key-count={{$keyCount}}
        - --total-writes={{$keyCount}}
        - --key-prefix={{$keyPrefix}}
        - --payload-type={{$payloadType}}
        - --compact-interval=0s
        - --defrag-interval=0s
        resources:
          requests:
            cpu: {{$cpu}}
            memory: {{$memory}}
          limits:
            cpu: {{$cpu}}
            memory: {{$memory}}
