{{$enableWatchListFeature := DefaultParam .CL2_ENABLE_WATCH_LIST_FEATURE false}}
{{$customApiCallThresholds := DefaultParam .CUSTOM_API_CALL_THRESHOLDS ""}}
{{$SINGLE_RESOURCE_API_LATENCY_THRESHOLD := DefaultParam .CL2_SINGLE_RESOURCE_API_LATENCY_THRESHOLD "1s"}}
{{$namespaces := 80}}
{{$podsPerNamespace := 1000}}
{{$testDuration := "5m"}}
name: watch-list
namespace:
  number: {{$namespaces}}
  prefix: "watch-list"
tuningSets:
- name: Uniform2000qps
  qpsLoad:
    qps: 2000
steps:
- name: Create pods
  phases:
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
      basename: watch-list
    replicasPerNamespace: {{$podsPerNamespace}}
    tuningSet: Uniform2000qps
    objectBundle:
    - basename: list-pod
      objectTemplatePath: "pod.yaml"
- name: Start measurements
  measurements:
    - Identifier: TestMetrics
      Method: TestMetrics
      Params:
        action: start
    - Identifier: WaitForFinishedJobs
      Method: WaitForFinishedJobs
      Params:
        action: start
        labelSelector: group = watch-list
    - Identifier: APIResponsivenessPrometheusSimple
      Method: APIResponsivenessPrometheus
      Params:
        action: start
- name: Start the informers
  phases:
    - replicasPerNamespace: 1
      tuningSet: Uniform2000qps
      objectBundle:
        - basename: watch-list-rbac
          objectTemplatePath: clusterrole.yaml
        - basename: watch-list-rbac
          objectTemplatePath: clusterrolebinding.yaml
          templateFillMap:
            JobNamespace: watch-list-1
    - namespaceRange:
        min: 1
        max: 1
        basename: watch-list
      replicasPerNamespace: 1
      tuningSet: Uniform2000qps
      objectBundle:
        - basename: watch-list
          objectTemplatePath: "job.yaml"
          templateFillMap:
            Duration: {{$testDuration}}
            EnableWatchListFeature: {{$enableWatchListFeature}}
- name: Starting measurement for waiting for informer pods to be running
  measurements:
  - Method: WaitForControlledPodsRunning
    Instances:
    - Identifier: WaitForRunningWatchListJobs
      Params:
        apiVersion: batch/v1
        kind: Job
    Params:
      action: start
      labelSelector: group = watch-list
      operationTimeout: 2m
- name: Waiting for informer pods to be running
  measurements:
  - Method: WaitForControlledPodsRunning
    Instances:
    - Identifier: WaitForRunningWatchListJobs
    Params:
      action: gather
- name: Wait for the informer job to finish
  measurements:
    - Identifier: WaitForFinishedJobs
      Method: WaitForFinishedJobs
      Params:
        action: gather
        timeout: 10m
- name: Collecting test measurements
  measurements:
    - Identifier: TestMetrics
      Method: TestMetrics
      Params:
        action: gather
    - Identifier: APIResponsivenessPrometheusSimple
      Method: APIResponsivenessPrometheus
      Params:
        action: gather
        enableViolations: true
        useSimpleLatencyQuery: true
        summaryName: APIResponsivenessPrometheus_simple
        customThresholds: {{YamlQuote $customApiCallThresholds 4}}
        singleResourceThreshold: {{$SINGLE_RESOURCE_API_LATENCY_THRESHOLD}}
