apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Name}}
  labels:
    group: watch-list
spec:
  template:
    metadata:
      labels:
        group: watch-list
    spec:
      containers:
        - name: {{.Name}}
          image: gcr.io/k8s-staging-perf-tests/perf-tests-util/request-benchmark:v0.0.12
          resources:
            requests:
              memory: "16Gi"
              cpu: "6"
            limits:
              memory: "16Gi"
              cpu: "6"
          command: [ "/benchmark" ]
          args: [ "informer", "--alsologtostderr=true", "--v=4", "--timeout={{.Duration}}", "--count=1", "--resource=pods", "--enableWatchListFeature={{.EnableWatchListFeature}}"]
      restartPolicy: Never
