apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Name}}
  labels:
    group: test-job
spec:
  parallelism: {{.Replicas}}
  completions: {{.Replicas}}
  completionMode: {{.Mode}}
  template:
    metadata:
      labels:
        group: test-pod
    spec:
      containers:
      - name: {{.Name}}
        image: registry.k8s.io/e2e-test-images/agnhost:2.56
        command:
          - sleep
          - {{.Sleep}}
      restartPolicy: Never
